version: '3'
services:
    jenkins:
        image: jenkinsci/blueocean
        environment:
          #### WINDOWS ONLY ####
          - DOCKER_HOST=tcp://host.docker.internal:2375
        user: root
        ports:
          - "8080:8080"
          - "8443:8443"
          - "50000:50000"
        volumes:
          - ./jenkins_data:/var/jenkins_home
        networks:
          - devnet
          
    nexus:
        image: sonatype/nexus3
        ports:
          - "8081:8081"
          - "8082:8082"
        volumes:
          - ./nexus_data:/nexus-data
        networks:
          - devnet
          
networks:
  devnet:
    driver: bridge
        